---
# tasks file for roles/web

- name: Docker Hub login
  docker_login:
    username: "{{ login }}"
    password: "{{ password }}"

- name: Pull image
  docker_image:
    name: dariazhdanovadev/cicd-exam-images:22
    source: pull
    state: present

- name: Run containers
  docker_container:
    name: "{{ item.key }}"
    image: dariazhdanovadev/cicd-exam-images:22
    published_ports:
      - "{{ item.value }}:5000"
    hostname: "{{ item.key }}"
    networks:
      - name: "{{ network }}"
        links: "{{ servers.keys() | list }}"
    state: started
    restart_policy: always
    cleanup: true
  loop: "{{ servers | dict2items }}"